# Generated by Django 4.1.7 on 2024-10-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='not_approved', max_length=20)),
            ],
        ),
    ]
