# Generated by Django 4.1.7 on 2024-10-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_student_admin'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.admin'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='staff',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='userauth.staff'),
            preserve_default=False,
        ),
    ]
