# Generated by Django 4.1.7 on 2024-10-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_student_admin'),
        ('inventory', '0003_inventory_category_inventory_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.staff'),
        ),
    ]
