# Generated by Django 4.1.7 on 2024-10-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_student_admin'),
        ('issue', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.staff'),
        ),
    ]
