# Generated by Django 4.1.7 on 2024-10-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('room_image', models.BinaryField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('occupancy', models.IntegerField()),
                ('vacancy', models.IntegerField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.admin')),
                ('amenities', models.ManyToManyField(related_name='rooms', to='rooms.amenity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.location')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCheckInStud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.student')),
            ],
            options={
                'db_table': 'room_check_in_stud',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn_date', models.DateField(blank=True, null=True)),
                ('checkOut_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=50)),
                ('duration', models.IntegerField(blank=True, choices=[(3, 3), (6, 6), (9, 9)], null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.student')),
            ],
        ),
    ]
