# Generated by Django 4.1.7 on 2024-10-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
