# Generated by Django 4.1.7 on 2024-10-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_location_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomCheckInStud',
        ),
    ]
