# Generated by Django 4.1.7 on 2024-10-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('rooms', '0004_alter_room_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel'),
        ),
    ]
