# Generated by Django 4.1.7 on 2024-10-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student', to='userauth.admin'),
        ),
    ]
